package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Documentos generated by hbm2java
 */
public class Documentos  implements java.io.Serializable {


     private Integer docId;
     private Integer proId;
     private String docNombre;
     private Date docFecha;
     private Boolean docEstado;
     private Integer idUsuario;

    public Documentos() {
    }

	
    public Documentos(Date docFecha) {
        this.docFecha = docFecha;
    }
    public Documentos(Integer proId, String docNombre, Date docFecha, Boolean docEstado, Integer idUsuario) {
       this.proId = proId;
       this.docNombre = docNombre;
       this.docFecha = docFecha;
       this.docEstado = docEstado;
       this.idUsuario = idUsuario;
    }
   
    public Integer getDocId() {
        return this.docId;
    }
    
    public void setDocId(Integer docId) {
        this.docId = docId;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getDocNombre() {
        return this.docNombre;
    }
    
    public void setDocNombre(String docNombre) {
        this.docNombre = docNombre;
    }
    public Date getDocFecha() {
        return this.docFecha;
    }
    
    public void setDocFecha(Date docFecha) {
        this.docFecha = docFecha;
    }
    public Boolean getDocEstado() {
        return this.docEstado;
    }
    
    public void setDocEstado(Boolean docEstado) {
        this.docEstado = docEstado;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }




}


