package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1



/**
 * PermisosPortafolio generated by hbm2java
 */
public class PermisosPortafolio  implements java.io.Serializable {


     private PermisosPortafolioId id;

    public PermisosPortafolio() {
    }

    public PermisosPortafolio(PermisosPortafolioId id) {
       this.id = id;
    }
   
    public PermisosPortafolioId getId() {
        return this.id;
    }
    
    public void setId(PermisosPortafolioId id) {
        this.id = id;
    }




}


