package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1



/**
 * PermisosDocumentosId generated by hbm2java
 */
public class PermisosDocumentosId  implements java.io.Serializable {


     private int usuId;
     private int docId;
     private int perId;

    public PermisosDocumentosId() {
    }

    public PermisosDocumentosId(int usuId, int docId, int perId) {
       this.usuId = usuId;
       this.docId = docId;
       this.perId = perId;
    }
   
    public int getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(int usuId) {
        this.usuId = usuId;
    }
    public int getDocId() {
        return this.docId;
    }
    
    public void setDocId(int docId) {
        this.docId = docId;
    }
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisosDocumentosId) ) return false;
		 PermisosDocumentosId castOther = ( PermisosDocumentosId ) other; 
         
		 return (this.getUsuId()==castOther.getUsuId())
 && (this.getDocId()==castOther.getDocId())
 && (this.getPerId()==castOther.getPerId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuId();
         result = 37 * result + this.getDocId();
         result = 37 * result + this.getPerId();
         return result;
   }   


}


