package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1



/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private Integer perId;
     private String perDescripcion;
     private Boolean perEstado;

    public Permisos() {
    }

    public Permisos(String perDescripcion, Boolean perEstado) {
       this.perDescripcion = perDescripcion;
       this.perEstado = perEstado;
    }
   
    public Integer getPerId() {
        return this.perId;
    }
    
    public void setPerId(Integer perId) {
        this.perId = perId;
    }
    public String getPerDescripcion() {
        return this.perDescripcion;
    }
    
    public void setPerDescripcion(String perDescripcion) {
        this.perDescripcion = perDescripcion;
    }
    public Boolean getPerEstado() {
        return this.perEstado;
    }
    
    public void setPerEstado(Boolean perEstado) {
        this.perEstado = perEstado;
    }




}


