package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1



/**
 * PermisosDocumentos generated by hbm2java
 */
public class PermisosDocumentos  implements java.io.Serializable {


     private PermisosDocumentosId id;

    public PermisosDocumentos() {
    }

    public PermisosDocumentos(PermisosDocumentosId id) {
       this.id = id;
    }
   
    public PermisosDocumentosId getId() {
        return this.id;
    }
    
    public void setId(PermisosDocumentosId id) {
        this.id = id;
    }




}


