package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Portafolios generated by hbm2java
 */
public class Portafolios  implements java.io.Serializable {


     private Integer proId;
     private Integer usuId;
     private String proNombre;
     private Date proFecha;
     private Boolean proEstado;

    public Portafolios() {
    }

	
    public Portafolios(Date proFecha) {
        this.proFecha = proFecha;
    }
    public Portafolios(Integer usuId, String proNombre, Date proFecha, Boolean proEstado) {
       this.usuId = usuId;
       this.proNombre = proNombre;
       this.proFecha = proFecha;
       this.proEstado = proEstado;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public Integer getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(Integer usuId) {
        this.usuId = usuId;
    }
    public String getProNombre() {
        return this.proNombre;
    }
    
    public void setProNombre(String proNombre) {
        this.proNombre = proNombre;
    }
    public Date getProFecha() {
        return this.proFecha;
    }
    
    public void setProFecha(Date proFecha) {
        this.proFecha = proFecha;
    }
    public Boolean getProEstado() {
        return this.proEstado;
    }
    
    public void setProEstado(Boolean proEstado) {
        this.proEstado = proEstado;
    }




}


