package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuId;
     private String usuRut;
     private String usuDv;
     private String usuNombres;
     private String usuApellidoPaterno;
     private String usuApellidoMaterno;
     private Boolean perEstado;
     private String usuPassword;

    public Usuario() {
    }

    public Usuario(String usuRut, String usuDv, String usuNombres, String usuApellidoPaterno, String usuApellidoMaterno, Boolean perEstado, String usuPassword) {
       this.usuRut = usuRut;
       this.usuDv = usuDv;
       this.usuNombres = usuNombres;
       this.usuApellidoPaterno = usuApellidoPaterno;
       this.usuApellidoMaterno = usuApellidoMaterno;
       this.perEstado = perEstado;
       this.usuPassword = usuPassword;
    }
   
    public Integer getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(Integer usuId) {
        this.usuId = usuId;
    }
    public String getUsuRut() {
        return this.usuRut;
    }
    
    public void setUsuRut(String usuRut) {
        this.usuRut = usuRut;
    }
    public String getUsuDv() {
        return this.usuDv;
    }
    
    public void setUsuDv(String usuDv) {
        this.usuDv = usuDv;
    }
    public String getUsuNombres() {
        return this.usuNombres;
    }
    
    public void setUsuNombres(String usuNombres) {
        this.usuNombres = usuNombres;
    }
    public String getUsuApellidoPaterno() {
        return this.usuApellidoPaterno;
    }
    
    public void setUsuApellidoPaterno(String usuApellidoPaterno) {
        this.usuApellidoPaterno = usuApellidoPaterno;
    }
    public String getUsuApellidoMaterno() {
        return this.usuApellidoMaterno;
    }
    
    public void setUsuApellidoMaterno(String usuApellidoMaterno) {
        this.usuApellidoMaterno = usuApellidoMaterno;
    }
    public Boolean getPerEstado() {
        return this.perEstado;
    }
    
    public void setPerEstado(Boolean perEstado) {
        this.perEstado = perEstado;
    }
    public String getUsuPassword() {
        return this.usuPassword;
    }
    
    public void setUsuPassword(String usuPassword) {
        this.usuPassword = usuPassword;
    }




}


