package model.entities;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Version generated by hbm2java
 */
public class Version  implements java.io.Serializable {


     private Integer verId;
     private Integer docId;
     private String verNumero;
     private Date verFecha;
     private String verComentario;
     private Integer idUsuario;

    public Version() {
    }

	
    public Version(Date verFecha) {
        this.verFecha = verFecha;
    }
    public Version(Integer docId, String verNumero, Date verFecha, String verComentario, Integer idUsuario) {
       this.docId = docId;
       this.verNumero = verNumero;
       this.verFecha = verFecha;
       this.verComentario = verComentario;
       this.idUsuario = idUsuario;
    }
   
    public Integer getVerId() {
        return this.verId;
    }
    
    public void setVerId(Integer verId) {
        this.verId = verId;
    }
    public Integer getDocId() {
        return this.docId;
    }
    
    public void setDocId(Integer docId) {
        this.docId = docId;
    }
    public String getVerNumero() {
        return this.verNumero;
    }
    
    public void setVerNumero(String verNumero) {
        this.verNumero = verNumero;
    }
    public Date getVerFecha() {
        return this.verFecha;
    }
    
    public void setVerFecha(Date verFecha) {
        this.verFecha = verFecha;
    }
    public String getVerComentario() {
        return this.verComentario;
    }
    
    public void setVerComentario(String verComentario) {
        this.verComentario = verComentario;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }




}


