package dacomment;
// Generated 27-10-2015 05:55:53 PM by Hibernate Tools 4.3.1



/**
 * PermisosPortafolioId generated by hbm2java
 */
public class PermisosPortafolioId  implements java.io.Serializable {


     private int perId;
     private int usuId;
     private int proId;

    public PermisosPortafolioId() {
    }

    public PermisosPortafolioId(int perId, int usuId, int proId) {
       this.perId = perId;
       this.usuId = usuId;
       this.proId = proId;
    }
   
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }
    public int getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(int usuId) {
        this.usuId = usuId;
    }
    public int getProId() {
        return this.proId;
    }
    
    public void setProId(int proId) {
        this.proId = proId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisosPortafolioId) ) return false;
		 PermisosPortafolioId castOther = ( PermisosPortafolioId ) other; 
         
		 return (this.getPerId()==castOther.getPerId())
 && (this.getUsuId()==castOther.getUsuId())
 && (this.getProId()==castOther.getProId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPerId();
         result = 37 * result + this.getUsuId();
         result = 37 * result + this.getProId();
         return result;
   }   


}


